openapi: 3.0.0
servers:
  - url: 'http://127.0.0.1:5000'
tags:
  - name: Index
    description: Index page
paths:
  /: 
    get:
      tags:
        - Index
      summary: Returns 'Hello, World!'
      responses:
        '200': 
          description: Successful Operation
          content:
            application/json:
              example:
                message: Hello, World!       
